### PR TITLE
fix: ctrl+l shortkey

### PR DESCRIPTION
**Pull request by Jan-Koll**
As mentioned in #3, the descriptions shown for the `Ctrl`+`L` were, as far as I know, not correct.
Additionally, I realized a bug, that the selected OS was ignored when filtering the shortkeys. 
This PR should fix both of that.

### CODE REVIEW

**Comment by tem-tem** [comment]
>  bug, that the selected OS was ignored when filtering the shortkeys

that's more like bad ux. Idea behind that switcher was to just change the marking for pressed buttons, and is not a filter for results. I'm thinking to work on filtering a little bit later - as soon as i implement reading all json files from given directory, so that we don't have to import each individual json file in the code; and add metadata into json structure. And then we could use the metadata for filtering. What do you think, @Jan-Koll ? Can we revert the filtering for now?

Also, with this implementation, safari is pretending to be a windows 😂 

image

**Comment by Jan-Koll** [comment]
Sure! Sorry, I assumed you had a filtering in mind when creating that switch. I'll revert that commit now.

> Also, with this implementation, safari is pretending to be a windows 😂

Oh yeah, you are right... forgot about that. 😅 Thanks for pointing this out.


Your ideas with the metadata etc sound great. However, I wonder what kind of metadata/structure are you planning exactly? Maybe something like this (just a rough idea)?
```json
{
	"shortcut": [["F5"]],
	"text": "Reload the current page",
	"browser": ["edge", "chrome", "brave", "firefox"],
	"os": ["mac", "windows", "linux"],
},
```
Then all shortcuts could be stored in a single file and one could filter to a certain browser version.

**Comment by tem-tem** [comment]
> what kind of metadata/structure are you planning exactly?

idk yet, haven't thought about it much to be honest)

**Review by tem-tem — APPROVED** [review]

**Comment by tem-tem** [comment]
@Jan-Koll noted your idea, will ping you once we are gonna be ready to work on that

**Pull request merged**
